name: CI/CD Node.js

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install

  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app-teste:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/app-teste:latest

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Cria uma pasta especifica para o projeto e entra nela
            mkdir -p ~/meu-app
            cd ~/meu-app

            # 2. Cria o arquivo .env com o usuario
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            
            # 3. Escreve o arquivo docker-compose.yml dentro da pasta
            cat << 'EOF' > docker-compose.yml
            services:
              api-teste:
                image: ${DOCKER_USERNAME}/app-teste:latest
                ports:
                  - "80:3000"
                restart: always
            EOF
            
            # 4. Baixa a imagem nova e reinicia o sistema
            docker pull ${{ secrets.DOCKER_USERNAME }}/app-teste:latest
            docker compose down
            docker compose up -d